site_name: 啊又一个博客

nav:
    - Home: index.md
    - Basics:
        - '信息论': 'basics/information_theory.md'
        - 'TF-IDF': 'basics/tfidf.md'

theme:
    name: 'material'
    palette:
        primary: 'teal'
        accent: 'teal'
    font:
        text: 'Noto Serif SC'
        code: 'Ubuntu Mono'
    logo:
        icon: 'local_cafe'

extra:
    social:
        - type: 'twitter'
          link: 'https://twitter.com/ailurus1991'

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
        emoji_index: !!python/name:pymdownx.emoji.emojione
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.keys

    - admonition
    - codehilite:
        guess_lang: true
        linenums: true
    - toc:
        permalink: true
        anchorlink: true